/*
 * SYNTHETIC samples for the "Load sample" buttons. Every name, identifier,
 * value and number is invented.
 *
 * GENERATED by tools/build-samples.js from samples/x12-835/ — do not edit by hand.
 */
(function (root) {
  'use strict';
  root.HCX.samples = root.HCX.samples || {};
  root.HCX.samples['x12-835'] = [
    { id: "remittance", label: "Remittance with a denial and a take-back", text: "ISA*00*          *00*          *ZZ*EXPAYER01      *ZZ*ACMEHOSP       *260921*1015*^*00501*000000101*0*P*:~\n" +
      "GS*HP*EXPAYER01*ACMEHOSP*20260921*1015*101*X*005010X221A1~\n" +
      "ST*835*0001~\n" +
      "BPR*I*1245.75*C*ACH*CCP*01*021000021*DA*9876543210*1512345678**01*011000015*DA*1234567890*20260921~\n" +
      "TRN*1*EFT20260921001*1512345678~\n" +
      "REF*EV*ACMEHOSP~\n" +
      "DTM*405*20260918~\n" +
      "N1*PR*EXAMPLE BLUE PLAN*XV*EXPAYER01~\n" +
      "N3*PO BOX 1000~\n" +
      "N4*JACKSONVILLE*FL*32201~\n" +
      "PER*CX*PROVIDER SERVICES*TE*8005550199*UR*WWW.EXAMPLE-PAYER.TEST~\n" +
      "N1*PE*ACME PRIMARY CARE WESTSIDE*XX*1234567893~\n" +
      "N3*500 EXAMPLE PKWY*SUITE 200~\n" +
      "N4*TAMPA*FL*33601~\n" +
      "REF*TJ*591234567~\n" +
      "LX*1~\n" +
      "TS3*1234567893*11*20261231*2*2425~\n" +
      "CLP*ACCT7788990*1*1800*1320.75*329.25*12*2026260001234*11*1~\n" +
      "NM1*QC*1*DOE*JANE*Q***MI*XEB123456789~\n" +
      "NM1*82*1*WELBY*MARCUS****XX*1234567890~\n" +
      "REF*1W*XEB123456789~\n" +
      "REF*6R*LINE-778899~\n" +
      "DTM*232*20260915~\n" +
      "DTM*233*20260915~\n" +
      "AMT*B6*1320.75~\n" +
      "SVC*HC:99214*250*180**1~\n" +
      "DTM*472*20260915~\n" +
      "CAS*CO*45*30~\n" +
      "CAS*PR*1*40~\n" +
      "SVC*HC:80053*1200*950.75**1~\n" +
      "DTM*472*20260915~\n" +
      "CAS*CO*45*80~\n" +
      "CAS*PR*1*100*PR*2*69.25~\n" +
      "SVC*HC:85025*350*190**1~\n" +
      "DTM*472*20260915~\n" +
      "CAS*CO*45*40~\n" +
      "CAS*PR*1*110*PR*2*10~\n" +
      "CLP*ACCT7788991*4*625*0*0*12*2026260001235*11*1~\n" +
      "NM1*QC*1*ROE*SAM****MI*XEB987654321~\n" +
      "REF*1W*XEB987654321~\n" +
      "DTM*232*20260916~\n" +
      "DTM*233*20260916~\n" +
      "CAS*CO*97*625~\n" +
      "MOA***N130*MA01~\n" +
      "SVC*HC:97110*625*0**4~\n" +
      "DTM*472*20260916~\n" +
      "CAS*CO*97*625~\n" +
      "LQ*HE*N130~\n" +
      "PLB*1234567893*20261231*WO:ACCT7712001*75~\n" +
      "SE*48*0001~\n" +
      "GE*1*101~\n" +
      "IEA*1*000000101~\n" +
      "" },
  ];
})(globalThis);
