/*
 * Regenerates standards/x12-835/sample.js from the files in samples/x12-835/.
 * The page cannot fetch those files when it is opened from disk, so they are
 * embedded as a script. Run `node tools/build-samples.js` after editing a
 * sample; a unit test fails if the two ever drift apart.
 */
'use strict';
const fs = require('node:fs');
const path = require('node:path');

const SAMPLES = [
  { id: 'remittance', label: 'Remittance with a denial and a take-back', file: 'example-payer-remittance.835' },
];
const repoRoot = path.join(__dirname, '..');

function asJsString(text) {
  return JSON.stringify(text).replace(/\\n/g, '\\n" +\n      "');
}

const entries = SAMPLES.map(({ id, label, file }) => {
  const text = fs.readFileSync(path.join(repoRoot, 'samples', 'x12-835', file), 'utf8');
  return `    { id: ${JSON.stringify(id)}, label: ${JSON.stringify(label)}, text: ${asJsString(text)} },`;
}).join('\n');

fs.writeFileSync(path.join(repoRoot, 'standards', 'x12-835', 'sample.js'), `/*
 * SYNTHETIC samples for the "Load sample" buttons. Every name, identifier,
 * value and number is invented.
 *
 * GENERATED by tools/build-samples.js from samples/x12-835/ — do not edit by hand.
 */
(function (root) {
  'use strict';
  root.HCX.samples = root.HCX.samples || {};
  root.HCX.samples['x12-835'] = [
${entries}
  ];
})(globalThis);
`);
console.log(`Wrote standards/x12-835/sample.js from ${SAMPLES.length} sample file(s).`);
